<?php

class Create_Users_Table{
       
  public function up()
  {
    /*
      verified : 
            公开权限表
            0 账号已注册，未激活邮箱，未审核资料 [都不能]
            1 账号已注册，已激活邮箱，未审核资料 [能搜索，不能被搜索到]
            2 账号已注册，已激活邮箱，已审核资料 [都可以，即能被搜索到]
            9 账号被封禁 [都不能]
    */
    Schema::create('users', function($table){
      $table->increments('id');
      $table->string('email', 128);
      $table->string('password', 100);
      $table->string('nickname', 100);
      $table->string('sex', 2);
      $table->integer('ethnic');
      $table->integer('nationality');
      $table->integer('height');
      $table->integer('weight');
      $table->integer('born');
      $table->integer('district');
      $table->integer('marriage');
      $table->integer('living');
      $table->integer('academic');
      $table->string('school', 10);
      $table->string('major', 10);
      $table->integer('industry');
      $table->integer('profession');
      $table->integer('companytype');
      $table->integer('salary');
      $table->string('blog', 100);
      $table->integer('verified');

      $table->timestamps();
    });

    DB::table('users')->insert(array(
      'email' => 'phoenix@test.com',
      'password' => Hash::make('password'),
      'nickname' => 'PHOENIX',
      'sex' => '男',
      'ethnic' => '1',
      'nationality' => '1',
      'height' => '170',
      'weight' => '54',
      'born' => '1989',
      'district' => '1',
      'marriage' => '1',
      'living' => '1',
      'academic' => '1',
      'school' => '华东师范大学',
      'major' => '地理',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '3',
      'blog' => 'blog.sample.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'tom@tom.com',
      'password' => Hash::make('123456'),
      'nickname' => 'TOM',
      'sex' => '男',
      'ethnic' => '1',
      'nationality' => '2',
      'height' => '173',
      'weight' => '54',
      'born' => '1977',
      'district' => '13',
      'marriage' => '1',
      'living' => '1',
      'academic' => '2',
      'school' => '上海大学',
      'major' => '经济',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '4',
      'blog' => 'blog.sample.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'marry@marry.com',
      'password' => Hash::make('password'),
      'nickname' => 'Marry',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '2',
      'height' => '173',
      'weight' => '54',
      'born' => '1987',
      'district' => '11',
      'marriage' => '1',
      'living' => '1',
      'academic' => '6',
      'school' => '复旦大学',
      'major' => '建筑',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '5',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'jerry@jerry.com',
      'password' => Hash::make('111111'),
      'nickname' => 'Jerry',
      'sex' => '女',
      'ethnic' => '2',
      'nationality' => '3',
      'height' => '111',
      'weight' => '66',
      'born' => '1980',
      'district' => '4',
      'marriage' => '2',
      'living' => '5',
      'academic' => '4',
      'school' => '纽约大学',
      'major' => '土木',
      'industry' => '5',
      'profession' => '2',
      'companytype' => '4',
      'salary' => '5',
      'blog' => 'blog.aaa.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'aaa@aaa.com',
      'password' => Hash::make('password'),
      'nickname' => 'Aaa',
      'sex' => '女',
      'ethnic' => '2',
      'nationality' => '4',
      'height' => '200',
      'weight' => '76',
      'born' => '1985',
      'district' => '3',
      'marriage' => '2',
      'living' => '1',
      'academic' => '7',
      'school' => '复旦大学',
      'major' => '建筑',
      'industry' => '1',
      'profession' => '4',
      'companytype' => '2',
      'salary' => '5',
      'blog' => 'blog.aaa.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'jack@jack.com',
      'password' => Hash::make('password'),
      'nickname' => 'Jack',
      'sex' => '男',
      'ethnic' => '1',
      'nationality' => '5',
      'height' => '186',
      'weight' => '54',
      'born' => '1978',
      'district' => '11',
      'marriage' => '1',
      'living' => '1',
      'academic' => '5',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '8',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'grubby@grubby.com',
      'password' => Hash::make('password'),
      'nickname' => 'Grubby',
      'sex' => '男',
      'ethnic' => '1',
      'nationality' => '1',
      'height' => '199',
      'weight' => '54',
      'born' => '1990',
      'district' => '15',
      'marriage' => '1',
      'living' => '1',
      'academic' => '6',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '6',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'dog@dog.com',
      'password' => Hash::make('password'),
      'nickname' => 'Dog',
      'sex' => '男',
      'ethnic' => '1',
      'nationality' => '1',
      'height' => '166',
      'weight' => '54',
      'born' => '1980',
      'district' => '11',
      'marriage' => '1',
      'living' => '1',
      'academic' => '6',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '6',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'blue@blue.com',
      'password' => Hash::make('password'),
      'nickname' => 'Blue',
      'sex' => '男',
      'ethnic' => '1',
      'nationality' => '5',
      'height' => '169',
      'weight' => '54',
      'born' => '1989',
      'district' => '15',
      'marriage' => '1',
      'living' => '1',
      'academic' => '4',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '7',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'yellow@yellow.com',
      'password' => Hash::make('password'),
      'nickname' => 'Grubby',
      'sex' => '男',
      'ethnic' => '1',
      'nationality' => '6',
      'height' => '171',
      'weight' => '54',
      'born' => '1985',
      'district' => '12',
      'marriage' => '1',
      'living' => '1',
      'academic' => '8',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '8',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'right@right.com',
      'password' => Hash::make('password'),
      'nickname' => 'Right',
      'sex' => '男',
      'ethnic' => '1',
      'nationality' => '7',
      'height' => '171',
      'weight' => '52',
      'born' => '1981',
      'district' => '11',
      'marriage' => '1',
      'living' => '1',
      'academic' => '5',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '9',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'left@left.com',
      'password' => Hash::make('password'),
      'nickname' => 'Left',
      'sex' => '男',
      'ethnic' => '1',
      'nationality' => '5',
      'height' => '177',
      'weight' => '74',
      'born' => '1981',
      'district' => '2',
      'marriage' => '1',
      'living' => '1',
      'academic' => '4',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '8',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'pink@pink.com',
      'password' => Hash::make('123456'),
      'nickname' => 'Jackie',
      'sex' => '男',
      'ethnic' => '1',
      'nationality' => '3',
      'height' => '173',
      'weight' => '64',
      'born' => '1985',
      'district' => '2',
      'marriage' => '1',
      'living' => '1',
      'academic' => '5',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '6',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'vanilla@vanilla.com',
      'password' => Hash::make('111111'),
      'nickname' => 'vanilla',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '4',
      'height' => '171',
      'weight' => '54',
      'born' => '1985',
      'district' => '2',
      'marriage' => '1',
      'living' => '1',
      'academic' => '6',
      'school' => '华东师范大学',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '8',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'openoffice@openoffice.com',
      'password' => Hash::make('123456'),
      'nickname' => 'Jamine',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '5',
      'height' => '181',
      'weight' => '64',
      'born' => '1989',
      'district' => '3',
      'marriage' => '1',
      'living' => '1',
      'academic' => '4',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '9',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'slow@slow.com',
      'password' => Hash::make('password'),
      'nickname' => 'Slow',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '4',
      'height' => '176',
      'weight' => '52',
      'born' => '1991',
      'district' => '3',
      'marriage' => '1',
      'living' => '1',
      'academic' => '4',
      'school' => '东华大学',
      'major' => '计算机',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '10',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'quick@quick.com',
      'password' => Hash::make('123456'),
      'nickname' => 'Quick',
      'sex' => '男',
      'ethnic' => '1',
      'nationality' => '3',
      'height' => '188',
      'weight' => '74',
      'born' => '1992',
      'district' => '4',
      'marriage' => '1',
      'living' => '1',
      'academic' => '5',
      'school' => '东华大学',
      'major' => '体育',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '11',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'mantou@mantou.com',
      'password' => Hash::make('password'),
      'nickname' => 'Mantou',
      'sex' => '男',
      'ethnic' => '1',
      'nationality' => '3',
      'height' => '173',
      'weight' => '58',
      'born' => '1989',
      'district' => '5',
      'marriage' => '1',
      'living' => '1',
      'academic' => '6',
      'school' => '华东理工',
      'major' => '生物',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '8',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'hehuan@hehuan.com',
      'password' => Hash::make('123456'),
      'nickname' => 'Hehuan',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '1',
      'height' => '172',
      'weight' => '64',
      'born' => '1990',
      'district' => '6',
      'marriage' => '1',
      'living' => '1',
      'academic' => '6',
      'school' => '华东理工',
      'major' => '地理',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '9',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'yinying@yinying.com',
      'password' => Hash::make('password'),
      'nickname' => 'Yinying',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '3',
      'height' => '171',
      'weight' => '54',
      'born' => '1982',
      'district' => '6',
      'marriage' => '1',
      'living' => '1',
      'academic' => '5',
      'school' => '同济大学',
      'major' => '土木建筑',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '7',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'jiamin@jiamin.com',
      'password' => Hash::make('password'),
      'nickname' => 'Jiamin',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '6',
      'height' => '175',
      'weight' => '64',
      'born' => '1991',
      'district' => '7',
      'marriage' => '1',
      'living' => '1',
      'academic' => '5',
      'school' => '同济大学',
      'major' => '土木建筑',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '8',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'juestin@juestin.com',
      'password' => Hash::make('123456'),
      'nickname' => 'Juestin',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '5',
      'height' => '175',
      'weight' => '51',
      'born' => '1995',
      'district' => '16',
      'marriage' => '1',
      'living' => '1',
      'academic' => '5',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '7',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'fly@fly.com',
      'password' => Hash::make('123456'),
      'nickname' => 'Fly',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '5',
      'height' => '176',
      'weight' => '64',
      'born' => '1985',
      'district' => '9',
      'marriage' => '1',
      'living' => '1',
      'academic' => '5',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '6',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'pie@pie.com',
      'password' => Hash::make('123456'),
      'nickname' => 'Pie',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '7',
      'height' => '166',
      'weight' => '52',
      'born' => '1988',
      'district' => '10',
      'marriage' => '1',
      'living' => '1',
      'academic' => '3',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '5',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'arduino@arduino.com',
      'password' => Hash::make('password'),
      'nickname' => 'Arduino',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '8',
      'height' => '177',
      'weight' => '64',
      'born' => '1988',
      'district' => '13',
      'marriage' => '1',
      'living' => '1',
      'academic' => '2',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '4',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'lake@lake.com',
      'password' => Hash::make('123456'),
      'nickname' => 'Lake',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '11',
      'height' => '173',
      'weight' => '54',
      'born' => '1988',
      'district' => '14',
      'marriage' => '1',
      'living' => '1',
      'academic' => '3',
      'school' => '华东理工',
      'major' => '机械制造',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '9',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'bob@bob.com',
      'password' => Hash::make('123456'),
      'nickname' => 'Bob',
      'sex' => '男',
      'ethnic' => '1',
      'nationality' => '11',
      'height' => '178',
      'weight' => '70',
      'born' => '1982',
      'district' => '15',
      'marriage' => '1',
      'living' => '1',
      'academic' => '4',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '6',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'netnat@netnat.com',
      'password' => Hash::make('password'),
      'nickname' => 'Netnat',
      'sex' => '男',
      'ethnic' => '1',
      'nationality' => '21',
      'height' => '171',
      'weight' => '52',
      'born' => '1986',
      'district' => '11',
      'marriage' => '1',
      'living' => '1',
      'academic' => '5',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '8',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));


    DB::table('users')->insert(array(
      'email' => 'verydog@verydog.com',
      'password' => Hash::make('password'),
      'nickname' => 'verydog',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '21',
      'height' => '172',
      'weight' => '53',
      'born' => '1986',
      'district' => '1',
      'marriage' => '1',
      'living' => '1',
      'academic' => '6',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '9',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));


    DB::table('users')->insert(array(
      'email' => 'slight@slight.com',
      'password' => Hash::make('password'),
      'nickname' => 'Slight',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '11',
      'height' => '173',
      'weight' => '52',
      'born' => '1987',
      'district' => '10',
      'marriage' => '1',
      'living' => '1',
      'academic' => '4',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '5',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'pinball@pinball.com',
      'password' => Hash::make('password'),
      'nickname' => 'Pinball',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '21',
      'height' => '175',
      'weight' => '64',
      'born' => '1988',
      'district' => '19',
      'marriage' => '1',
      'living' => '1',
      'academic' => '5',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '7',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'lolly@lolly.com',
      'password' => Hash::make('password'),
      'nickname' => 'Lolly',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '22',
      'height' => '174',
      'weight' => '52',
      'born' => '1986',
      'district' => '17',
      'marriage' => '1',
      'living' => '1',
      'academic' => '5',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '12',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));


    DB::table('users')->insert(array(
      'email' => 'what@what.com',
      'password' => Hash::make('password'),
      'nickname' => 'What',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '12',
      'height' => '163',
      'weight' => '44',
      'born' => '1988',
      'district' => '18',
      'marriage' => '1',
      'living' => '1',
      'academic' => '5',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '13',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'whatever@whatever.com',
      'password' => Hash::make('password'),
      'nickname' => 'Whatever',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '12',
      'height' => '165',
      'weight' => '54',
      'born' => '1987',
      'district' => '1',
      'marriage' => '1',
      'living' => '1',
      'academic' => '5',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '15',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'evernote@evernote.com',
      'password' => Hash::make('password'),
      'nickname' => 'Evernote',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '13',
      'height' => '161',
      'weight' => '42',
      'born' => '1987',
      'district' => '12',
      'marriage' => '1',
      'living' => '1',
      'academic' => '5',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '9',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));


    DB::table('users')->insert(array(
      'email' => 'rice@rice.com',
      'password' => Hash::make('password'),
      'nickname' => 'Rice',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '11',
      'height' => '162',
      'weight' => '46',
      'born' => '1988',
      'district' => '3',
      'marriage' => '1',
      'living' => '1',
      'academic' => '5',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '7',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'gogogo@gogogo.com',
      'password' => Hash::make('password'),
      'nickname' => 'Gogogo',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '16',
      'height' => '171',
      'weight' => '54',
      'born' => '1985',
      'district' => '4',
      'marriage' => '1',
      'living' => '1',
      'academic' => '5',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '5',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));


    DB::table('users')->insert(array(
      'email' => 'zazzy@zazzy.com',
      'password' => Hash::make('password'),
      'nickname' => 'Zazzy',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '12',
      'height' => '171',
      'weight' => '54',
      'born' => '1985',
      'district' => '2',
      'marriage' => '1',
      'living' => '1',
      'academic' => '5',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '10',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

    DB::table('users')->insert(array(
      'email' => 'alex@alex.com',
      'password' => Hash::make('password'),
      'nickname' => 'Alex',
      'sex' => '女',
      'ethnic' => '1',
      'nationality' => '11',
      'height' => '175',
      'weight' => '64',
      'born' => '1986',
      'district' => '3',
      'marriage' => '1',
      'living' => '1',
      'academic' => '3',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '7',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));
    
    DB::table('users')->insert(array(
      'email' => 'coffee@coffee.com',
      'password' => Hash::make('password'),
      'nickname' => 'Coffee',
      'sex' => '男',
      'ethnic' => '1',
      'nationality' => '1',
      'height' => '174',
      'weight' => '52',
      'born' => '1989',
      'district' => '4',
      'marriage' => '1',
      'living' => '1',
      'academic' => '4',
      'school' => '华东政法',
      'major' => '法律',
      'industry' => '1',
      'profession' => '1',
      'companytype' => '1',
      'salary' => '2',
      'blog' => 'blog.test.com',
      'verified' => '0',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s')
    ));

  }

  public function down()
  {
    Schema::drop('users');
  }
}